In [96]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
import numpy as np

In [103]:
policy=pd.read_csv("policies.csv")
policy.reset_index(drop=True)
policy.head()
#policy.set_index("date",inplace=True)
#policy.index=pd.to_datetime(policy.index)
policy.drop(policy.columns[0], axis=1, inplace=True)
policy.columns

Index(['country_code', 'country_name', 'date', 'stringency_index',
       'government_response_index', 'containment_health_index',
       'economic_support_index', 'c1_school_closing', 'c1_flag',
       'c2_workplace_closing', 'c2_flag', 'c3_cancel_public_events', 'c3_flag',
       'c4_restrictions_on_gatherings', 'c4_flag', 'c5_close_public_transport',
       'c5_flag', 'c6_stay_at_home_requirements', 'c6_flag',
       'c7_movementrestrictions', 'c7_flag', 'c8_internationaltravel',
       'e1_income_support', 'e1_flag', 'e2_debtrelief',
       'h1_public_information_campaigns', 'h1_flag', 'h2_testing_policy',
       'h3_contact_tracing', 'h6_facial_coverings', 'h6_flag',
       'h7_vaccination_policy', 'h7_flag', 'h8_protection_of_elderly_people',
       'h8_flag', 'confirmed_cases', 'confirmed_deaths'],
      dtype='object')

In [104]:
c=[8,10,12,14,16,18,20,22,23,25,26,28,29,30,32,34]
for i in c:
    print(policy.columns[i-1])

c1_school_closing
c2_workplace_closing
c3_cancel_public_events
c4_restrictions_on_gatherings
c5_close_public_transport
c6_stay_at_home_requirements
c7_movementrestrictions
c8_internationaltravel
e1_income_support
e2_debtrelief
h1_public_information_campaigns
h2_testing_policy
h3_contact_tracing
h6_facial_coverings
h7_vaccination_policy
h8_protection_of_elderly_people

## For each policy, divide it by the maximum possible and make it a percentage

In [105]:
for i in c:
    my_max = policy[policy.columns[i-1]].loc[policy[policy.columns[i-1]].idxmax()]
    policy[policy.columns[i-1]]=policy[policy.columns[i-1]] / my_max *100
    policy[policy.columns[i-1]]=policy[policy.columns[i-1]].apply(lambda x: x if np.isnan(x) else int(x))

In [106]:
df = pd.read_csv('owid-covid-data.csv')
df.reset_index(drop=True)
df.columns = df.columns.str.replace('location', 'country_name')
df.tail()

,iso_code,continent,country_name,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
155852,ZWE,Africa,Zimbabwe,2022-01-15,225637.0,0.0,531.286,5238.0,0.0,12.857,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
155853,ZWE,Africa,Zimbabwe,2022-01-16,226078.0,441.0,594.286,5247.0,9.0,14.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
155854,ZWE,Africa,Zimbabwe,2022-01-17,226460.0,382.0,494.286,5258.0,11.0,11.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
155855,ZWE,Africa,Zimbabwe,2022-01-18,226460.0,0.0,494.286,5258.0,0.0,11.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
155856,ZWE,Africa,Zimbabwe,2022-01-19,226887.0,427.0,350.571,5266.0,8.0,7.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [107]:
policy_cases=policy.merge(df, on=['date','country_name'])
policy_cases.tail()

,country_code,country_name,date,stringency_index_x,government_response_index,containment_health_index,economic_support_index,c1_school_closing,c1_flag,c2_workplace_closing,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
121746,ZWE,Zimbabwe,2022-01-15,40.74,40.1,45.83,0.0,0.0,NaN,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
121747,ZWE,Zimbabwe,2022-01-16,40.74,40.1,45.83,0.0,0.0,NaN,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
121748,ZWE,Zimbabwe,2022-01-17,40.74,40.1,45.83,0.0,0.0,NaN,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
121749,ZWE,Zimbabwe,2022-01-18,40.74,40.1,45.83,0.0,0.0,NaN,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
121750,ZWE,Zimbabwe,2022-01-19,40.74,40.1,45.83,0.0,0.0,NaN,0.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [110]:
policy_cases.columns
policy_cases.drop(['iso_code','confirmed_cases','confirmed_deaths'], axis=1, inplace=True)
print([i for i in policy_cases.columns])

In [112]:
policy_cases=policy_cases.reindex(columns = ['country_code', 'country_name','continent','date', 'stringency_index_x', 'government_response_index', 'containment_health_index', 'economic_support_index', 'c1_school_closing', 'c1_flag', 'c2_workplace_closing', 'c2_flag', 'c3_cancel_public_events', 'c3_flag', 'c4_restrictions_on_gatherings', 'c4_flag', 'c5_close_public_transport', 'c5_flag', 'c6_stay_at_home_requirements', 'c6_flag', 'c7_movementrestrictions', 'c7_flag', 'c8_internationaltravel', 'e1_income_support', 'e1_flag', 'e2_debtrelief', 'h1_public_information_campaigns', 'h1_flag', 'h2_testing_policy', 'h3_contact_tracing', 'h6_facial_coverings', 'h6_flag', 'h7_vaccination_policy', 'h7_flag', 'h8_protection_of_elderly_people', 'h8_flag', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 'stringency_index_y', 'population', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million'])
#policy_cases.to_csv("all_normalized.csv")

,country_code,country_name,continent,date,stringency_index_x,government_response_index,containment_health_index,economic_support_index,c1_school_closing,c1_flag,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,ABW,Aruba,North America,2020-03-13,0.00,2.08,2.38,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,76.29,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,North America,2020-03-14,0.00,2.08,2.38,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,76.29,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,North America,2020-03-15,0.00,2.08,2.38,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,76.29,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,North America,2020-03-16,11.11,8.33,9.52,0.0,100.0,1.0,...,NaN,NaN,NaN,NaN,76.29,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,North America,2020-03-17,22.22,14.58,16.67,0.0,100.0,1.0,...,NaN,NaN,NaN,NaN,76.29,NaN,NaN,NaN,NaN,NaN